project_name: "argocd-vault-plugin"

builds:
  - binary: "argocd-vault-plugin"
    flags: "-trimpath"
    ldflags: >-
      -s -w
      -X "github.com/argoproj-labs/argocd-vault-plugin/version.Version={{.Tag}}"
      -X "github.com/argoproj-labs/argocd-vault-plugin/version.BuildDate={{.Date}}"
      -X "github.com/argoproj-labs/argocd-vault-plugin/version.CommitSHA={{.Commit}}"
    env:
      - "CGO_ENABLED=1"
      - "C=musl-gcc"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - s390x
    ignore:
      - goos: darwin
        goarch: s390x
    tags:
      - netgo
      - static_build

archives:
  - format: binary

changelog:
  skip: true
