# Using avp.kubernetes.io/secret-version  Annotation
# We are setting avp.kubernetes.io/secret-version to tell the plugin which version of a secret to use
# This annotation can be overridden with an inline-path placeholder
# <username> will be filled in with the `username` key's value at version a3234dc
# <password> will be filled in with the `password` key's value at version b48546d
kind: Secret
apiVersion: v1
metadata:
  name: example-versioned
  annotations:
    avp.kubernetes.io/path: "custom-secret-manager/database"
    avp.kubernetes.io/secret-version: "a3234dc"
type: Opaque
data:
  username: <username>
  password: <path:custom-secret-manager/database#password#b48546d>