name: mkdocs
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Setup deps
        run: |
          pip install mkdocs-material 
          pip install mike
          sudo apt-get install -y pcregrep
      - name: Publish docs
        run: | 
          export REF=$(echo $GITHUB_REF | pcregrep --only-matching=1 ".*\/.*\/(.*)")
          git config user.name mkdocs
          git config user.email noreply@null.com 
          git fetch origin gh-pages --depth=1
          mike deploy -u -p --rebase $REF $(if [ $REF == "main" ]; then echo preview; else echo stable; fi)