name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  linux:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Download deps
        run: docker build . -t ci

      # Disable network so that Azure specific behavior doesn't happen
      - name: Quality
        run: docker run --network none --env GOPATH="" --rm -v $PWD:/go/work ci make quality

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Build and test plugin
        run: docker run --network none --env GOPATH="" --rm -v $PWD:/go/work ci make e2e
  mac:
    strategy:
      fail-fast: false
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.17.8

      - name: Quality checks
        run: make quality

      - name: Build and test plugin
        run: make e2e
